# 라이브러리

In [3]:
import MeCab
import konlpy
from sklearn.feature_extraction.text import CountVectorizer
import re


# 필요 라이브러리 임포트
import tensorflow as tf
import bert
import os
# from konlpy.tag import Mecab
import pandas as pd
import numpy as np
from tensorflow import keras
from tensorflow.keras.layers import Dense
from tqdm import tqdm
from korpat_tokenizer import Tokenizer

import plotly.graph_objects as og
import cufflinks as cf
import chart_studio.plotly as py
from konlpy.tag import Mecab
cf.go_offline(connected = True)


In [2]:
import pandas as pd
import cufflinks as cf
import chart_studio.plotly as py
import plotly.graph_objects as go

cf.go_offline(connected= True)

from sklearn.decomposition import LatentDirichletAllocation

In [5]:
direct = 'C:/Users/USER/Documents/Jupyter Notebook/AI_IMEN/korpatbert_v1.0/pretrained/'

df_block = pd.read_csv('블록체인_2_상세.csv',index_col = 0).reset_index(drop = True)
df_ML = pd.read_csv('머신러닝_상세.csv',index_col = 0).reset_index(drop = True)
df_supply = pd.read_csv('유통_상세.csv',index_col = 0).reset_index(drop = True)

In [9]:
df_all = pd.concat([df_block,df_ML,df_supply], axis=0)

In [30]:
df_all_2 = df_all[df_all['요약'].notnull()]

In [31]:
df_all_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24612 entries, 0 to 7519
Data columns (total 29 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   (51) Int. CL      24612 non-null  object 
 1   (52) CPC          24612 non-null  object 
 2   (21) 출원번호/일자      22079 non-null  object 
 3   (71) 출원인          24612 non-null  object 
 4   (11) 등록번호/일자      14211 non-null  object 
 5   (65) 공개번호/일자      18592 non-null  object 
 6   (11) 공고번호/일자      0 non-null      float64
 7   (86) 국제출원번호/일자    2532 non-null   object 
 8   (87) 국제공개번호/일자    24612 non-null  object 
 9   (30) 우선권정보        24612 non-null  object 
 10  법적상태              24612 non-null  object 
 11  심사진행상태            24612 non-null  object 
 12  심판사항              24612 non-null  object 
 13  구분                24612 non-null  object 
 14  원출원번호/일자          1272 non-null   object 
 15  관련 출원번호           24612 non-null  object 
 16  기술이전 희망           140 non-null    object 

In [32]:
df_all_2['(52) CPC ']

0       ['G06Q40/04(2013.01)', 'G06Q20/38(2013.01)', '...
1       ['H04L9/0825(2013.01)', 'H04L67/1044(2013.01)'...
2       ['H04L9/085(2013.01)', 'H04L9/0825(2013.01)', ...
3       ['G06F21/6245(2013.01)', 'G06F21/31(2013.01)',...
4            ['G06Q40/06(2013.01)', 'G06Q40/04(2013.01)']
                              ...                        
7515    ['A61F13/0286(2013.01)', 'A61F13/00063(2013.01...
7516    ['B65H35/04(2013.01)', 'B65H16/005(2013.01)', ...
7517    ['A41D27/08(2013.01)', 'A41D1/06(2013.01)', 'A...
7518         ['B65D81/03(2013.01)', 'B65D65/44(2013.01)']
7519    ['B02C4/06(2013.01)', 'B02C4/286(2013.01)', 'B...
Name: (52) CPC , Length: 24612, dtype: object

In [35]:
df_all_2['(52) CPC '].isnull().value_counts()

False    24612
Name: (52) CPC , dtype: int64

In [34]:
lst_all = []
lst_all_2 = []
for idx,i in enumerate(df_all_2['(52) CPC ']):
    lst_a = []
    for j in i.replace('[','').replace(']','').split("'"):
        if len(j.strip()) != 1:
            lst_a.append(j.split('(')[0])
#                 if len(k.replace('\n','').replace('.....','').strip()) != 0:
#                     lst_a.append(k)
#                 else:
#                     lst_a.append('')
            lst_a = [item[:4] for item in lst_a if item != '' and item != '\n' and item != '.....']
            
        
    lst_all.append(set(lst_a))
    lst_all_2 += lst_a
    

In [36]:
lst_all

[{'G06F', 'G06Q'},
 {'G06F', 'H04L'},
 {'G06F', 'H04L'},
 {'G06F', 'H04L'},
 {'G06Q'},
 {'G06F', 'H04L'},
 {'G06Q', 'H04L', 'Y02P'},
 {'H04L'},
 {'G06Q'},
 {'G06F', 'G06T', 'G06V', 'G16H', 'H04L'},
 {'G06F', 'G06Q', 'H04L'},
 {'G06F', 'G06N', 'G06Q'},
 {'G06Q', 'H04L'},
 {'G06F', 'G06Q', 'H04L'},
 {'G06F', 'G06Q', 'H04L'},
 {'G06Q'},
 {'G06F', 'H04L'},
 {'G06Q'},
 {'G06Q', 'H04L', 'Y04S'},
 {'G06Q', 'H04L'},
 {'H04L'},
 {'G06Q', 'H04L', 'Y04S'},
 {'G06Q'},
 {'G06Q', 'H04L'},
 {'G06Q', 'H04L'},
 {'G06F', 'G16H'},
 {'G06Q'},
 {'G06Q', 'H04L'},
 {'G06Q'},
 {'G06Q', 'H04L'},
 {'G06Q', 'G06V', 'H04L'},
 {'G06F', 'G06K', 'G06N', 'G06Q', 'G06T', 'H04L'},
 {'G06Q'},
 {'G06Q', 'G06V', 'H04L'},
 {'G06F', 'G06Q', 'H04L'},
 {'G06K', 'G06Q', 'H04L'},
 {'G06Q'},
 {'H04L'},
 {'G06Q', 'H04L'},
 {'G06K', 'G06Q'},
 {'H04L'},
 {'G06Q', 'H02J', 'H04L'},
 {'G06Q', 'H02J', 'Y04S'},
 {'H04L'},
 {'G06Q'},
 {'G06F', 'G06Q', 'H04L'},
 {'G06F'},
 {'G06F', 'H04L'},
 {'G06F'},
 {'G06Q'},
 {'G05B', 'H04L'},
 {'G06Q

In [37]:
df_all_2['IPC_remake'] = lst_all

In [38]:
df_all_2[['IPC_remake']].isnull().value_counts()

IPC_remake
False         24612
dtype: int64

In [39]:
fe = 0
for i in lst_all:
    fe = max(fe, len(i))
    
print(fe)

12


In [47]:
df_all_2_small = df_all_2[['IPC_remake','요약']].copy()

In [48]:
df_all_2_small.isnull().value_counts()

IPC_remake  요약   
False       False    24612
dtype: int64

In [116]:
dict_all = {'a':'', 'b':'','c':'','d':''}
''.join(list(dict_all.values()))
len(''.join(list(dict_all.values())))

0

In [119]:
import tqdm

lst_a = []

df_all_2_small['same_patent'] = 0

for idx,i in zip(tqdm.tqdm(df_all_2_small.index) ,df_all_2_small['IPC_remake']):
    
    dict_all = {'a':'', 'b':'','c':'','d':''}

    if ('G06Q' in i):
        dict_all['a'] = 'A'
    if ('G06N' in i):
        dict_all['b']= 'B'
    if ('H04L' in i):
        dict_all['c'] = 'C'

    if len(''.join(list(dict_all.values()))) == 0:
        dict_all['d'] = 'E'
        
    
    

    df_all_2_small.loc[idx,'same_patent'] = dict_all['a'] + dict_all['b'] + dict_all['c'] + dict_all['d']

100%|██████████████████████████████████████████████████████████████████████████| 24612/24612 [00:10<00:00, 2253.96it/s]


In [121]:
df_all_2_small['same_patent'].value_counts()

E      18194
A       5224
B        385
AC       332
AB       243
C        180
ABC       28
BC        26
Name: same_patent, dtype: int64

In [122]:
df_all_2['same_patent'] = df_all_2_small['same_patent'].copy()

In [123]:
# df_block_2.to_csv('블록체인_same_patent.csv',encoding = 'utf-8-sig')

# LDA

In [124]:
df_A = df_all_2[['same_patent','요약']]

In [125]:
tokenizer = Tokenizer(vocab_path=direct + "korpat_vocab.txt", cased=True)

In [126]:
df_A['same_patent'] = [i if len(i) != 0 else 'D' for i in df_A['same_patent'] ]

In [127]:
df_A.isnull().sum()

same_patent    0
요약             0
dtype: int64

In [128]:
df_A_2 = df_A.dropna()

In [129]:
tokenizer = Tokenizer(vocab_path=direct + "korpat_vocab.txt", cased=True)

In [130]:
def make_tokenizer(row):
    row = tokenizer.tokenize(row)
    return row
    
df_A_3 = df_A_2.set_index('same_patent').copy()

In [131]:
from tqdm import tqdm
tqdm.pandas()

In [132]:
B = df_A_3['요약'].progress_apply(make_tokenizer).copy()

100%|███████████████████████████████████████████████████████████████████████████| 24612/24612 [00:46<00:00, 530.42it/s]


In [161]:
df_B = df_A_3.copy()
df_B['요약'] = B


In [162]:
title_lst = [i for i in df_B['요약'] if len(i) >= 1]

In [163]:
df_B.index.value_counts()

E      18194
A       5224
B        385
AC       332
AB       243
C        180
ABC       28
BC        26
Name: same_patent, dtype: int64

In [209]:
df_C = df_B[df_B.index != 'E'].copy()

In [210]:
title_lst = [i for i in df_C['요약'] if len(i) >= 1]

In [211]:
import re

def hasNumber(stringVal):
    if (re.search('\d', stringVal) == None):
        return False
    else:
        return True
    
    
def hasEnglish(stringVal):
    if (re.search('[A-Za-z]',stringVal) == None):
        return False
    else:
        return True
    
    
    
def hasSpecial(stringVal):
    if (re.search('[-=+,#/\?:^.@*\"※~ㆍ!』‘|\(\)\[\]`\'…》\”\“\’·]',stringVal) == None):
        return False
    else:
        return True

<>:4: DeprecationWarning:

invalid escape sequence \d

<>:19: DeprecationWarning:

invalid escape sequence \?

<>:4: DeprecationWarning:

invalid escape sequence \d

<>:19: DeprecationWarning:

invalid escape sequence \?

<>:4: DeprecationWarning:

invalid escape sequence \d

<>:19: DeprecationWarning:

invalid escape sequence \?

<ipython-input-211-172c02ca9a37>:4: DeprecationWarning:

invalid escape sequence \d

<ipython-input-211-172c02ca9a37>:19: DeprecationWarning:

invalid escape sequence \?



In [212]:
title_lst_2 = []

for cols in tqdm(title_lst):
    title_lst_small = []
    for col in cols:
        if (hasNumber(col)) or (hasEnglish(col)) or (hasNumber(col)) or (len(col) <= 1) or ('#' in col):
            pass
        else:
            title_lst_small.append(col)
            
    title_lst_2.append(title_lst_small)

100%|████████████████████████████████████████████████████████████████████████████| 6418/6418 [00:03<00:00, 1754.60it/s]


In [213]:
title_lst_3 = [i for i in title_lst_2 if len(i) >= 1]

In [214]:
len(title_lst_3)

6417

In [215]:
lst_all = title_lst_3

In [242]:
from konlpy.tag import Mecab
from tqdm import tqdm
import re
from gensim.models.ldamodel import LdaModel
from gensim.models.callbacks import CoherenceMetric
from gensim import corpora
from gensim.models.callbacks import PerplexityMetric
import logging
import pickle
import pyLDAvis.gensim_models
from gensim.models.coherencemodel import CoherenceModel
import matplotlib.pyplot as plt


if __name__ == '__main__':


    # 정수 인코딩과 빈도수 생성
    dictionary = corpora.Dictionary(lst_all)

    # 출현빈도가 적거나 자주 등장하는 단어는 제거
    dictionary.filter_extremes(no_below=10, no_above=0.05)
    
    corpus = [dictionary.doc2bow(text) for text in lst_all]
    print('Number of unique tokens: %d' % len(dictionary))
    print('Number of documents: %d' % len(corpus))
    
    perplexity_logger = PerplexityMetric(corpus=corpus, logger='shell')
    coherence_logger = CoherenceMetric(corpus=corpus, coherence="u_mass", logger='shell')



    lda_model = LdaModel(corpus, id2word = dictionary,alpha='auto', num_topics=7, passes=30, callbacks=[coherence_logger, perplexity_logger])
    
    coherence_model_lda = CoherenceModel(model=lda_model, texts=lst_all, dictionary=dictionary, coherence='c_v')
    coherence_lda = coherence_model_lda.get_coherence()
    print('\nCoherence Score (c_v): ', coherence_lda)

    # Compute Coherence Score using UMass
    coherence_model_lda = CoherenceModel(model=lda_model, texts=lst_all, dictionary=dictionary, coherence="u_mass")
    coherence_lda = coherence_model_lda.get_coherence()
    print('\nCoherence Score (u_mass): ', coherence_lda)


    # 저장
    pickle.dump(corpus, open('corpus.pkl', 'wb'))
    dictionary.save('lda_dictionary.gensim')
    lda_model.save('lda_model.gensim')

    # pyLDAvis html 저장
    lda_visualization = pyLDAvis.gensim_models.prepare(lda_model, corpus, dictionary, sort_topics=False)
    pyLDAvis.save_html(lda_visualization, 'testing_5.html')
    pyLDAvis.display(lda_visualization)



Number of unique tokens: 2459
Number of documents: 6417

Coherence Score (c_v):  0.3835363109687925

Coherence Score (u_mass):  -6.808523862984397


In [243]:
for idx, cols in tqdm(enumerate(title_lst)):
    title_lst_small = []
    for col in cols:
        if (hasNumber(col)) or (hasEnglish(col)) or (hasNumber(col)) or (len(col) <= 1) or ('#' in col):
            pass
        else:
            title_lst_small.append(col)
            
    if len(title_lst_small) == 0:
        print(idx)

3565it [00:01, 1983.45it/s]

3124


6418it [00:03, 1773.02it/s]


In [244]:
df_C_2 = df_C.reset_index()[df_C.reset_index().index != 3124].set_index('same_patent').copy()

In [245]:
topic_dist = pd.get_dummies(df_C_2.index).values

In [246]:
df_C_2.index

Index(['AC', 'A', 'AB', 'A', 'A', 'A', 'A', 'AC', 'AB', 'A',
       ...
       'A', 'A', 'A', 'C', 'A', 'C', 'A', 'A', 'A', 'A'],
      dtype='object', name='same_patent', length=6417)

In [247]:
pd.Series(df_C_2.index).drop_duplicates().sort_index()

0        AC
1         A
2        AB
10        C
31      ABC
843       B
1791     BC
Name: same_patent, dtype: object

In [248]:
name = {"AC" : 4 , "A" :1 ,"AB" : 2, "C" : 7 , 'ABC' : 3, "B" : 5, "BC": 6}
topic_dist[0],topic_dist[1],topic_dist[2],topic_dist[10],topic_dist[31],topic_dist[843],topic_dist[1791]


(array([0, 0, 0, 1, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0, 0, 0], dtype=uint8),
 array([0, 0, 0, 0, 0, 0, 1], dtype=uint8),
 array([0, 0, 1, 0, 0, 0, 0], dtype=uint8),
 array([0, 0, 0, 0, 1, 0, 0], dtype=uint8),
 array([0, 0, 0, 0, 0, 1, 0], dtype=uint8))

In [249]:
sorted(name.items(), key=lambda x: x[1])

[('A', 1), ('AB', 2), ('ABC', 3), ('AC', 4), ('B', 5), ('BC', 6), ('C', 7)]

In [176]:
df_B_2.index

Index(['E', 'AC', 'A', 'AB', 'A', 'A', 'A', 'A', 'E', 'AC',
       ...
       'A', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E'],
      dtype='object', name='same_patent', length=24611)

In [255]:
df_C_2['lst']  = lst_all

In [258]:
# df_C_2.to_csv('ABC.csv',encoding = 'utf-8-sig')

In [250]:
df_C_2.index.value_counts() # 이거와 역순으로 LDA가 만들어짐.(밑에서부터 시작한다고 보면 됨)
# 나머지 값들중 가지고 있는 것들을 봄.

A      5223
B       385
AC      332
AB      243
C       180
ABC      28
BC       26
Name: same_patent, dtype: int64

In [251]:
from scipy.sparse import csr_matrix

In [252]:
csr_matrix(topic_dist.T)

<7x6417 sparse matrix of type '<class 'numpy.uint8'>'
	with 6417 stored elements in Compressed Sparse Row format>

In [253]:
lda_visualization = pyLDAvis.gensim_models.prepare(lda_model, corpus, dictionary, 
                                                   sort_topics=False,
                                                    doc_topic_dist=csr_matrix(topic_dist.T))
pyLDAvis.save_html(lda_visualization, 'make_l_LDA_3.html',)
pyLDAvis.display(lda_visualization)

In [108]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [109]:
class_le = LabelEncoder()
y_label = class_le.fit_transform( df_B_2.index)
y_label


array([3, 6, 6, ..., 7, 7, 7])

In [114]:
len(y_label)

8535